- name: Выполнение shell скрипта ({{ task }})
  shell: >
    cd "{{ role_path_files }}" &&
    docker compose rm -fsv;
    docker rmi "{{ control_settings.docker.compose.names.image }}";
  async: "{{ control_settings.mode.start_stop_timeout_poll[0] | int }}"
  poll: "{{ control_settings.mode.start_stop_timeout_poll[1] | int }}"
  register: shell_result
  failed_when: not true and not false  # т.е. never

- include_tasks: show_shell_error.yml
  vars: { time: "{{ control_settings.mode.start_stop_timeout_poll[0] }}" }