---
- name: Выполнение shell скрипта ({{ task }})
  shell: 'cd "{{ role_path_files }}" && docker compose start'
  async: "{{ mode.start_stop_timeout_poll[0] | int }}"
  poll: "{{ mode.start_stop_timeout_poll[1] | int }}"
  register: shell_result
  failed_when: not true and not false  # т.е. never

- include_tasks: show_shell_error.yml
  vars: { time: "{{ mode.start_stop_timeout_poll[0] }}" }