- name: Установка программ из репозитория
  hosts: "{{ host_for_play | default('virtual_box') }}"  # all
  become: yes

  tasks:  # dpkg --get-selections > mylist.list

  - include_role:
      name: apt_install_uninstall