all:
  children:
    local:
      hosts:
        asus_x751_ln:  # alias
          ansible_host: 127.0.0.1
          ansible_port: 40002
      children:
        virtual_box:
          hosts:
            linux_mint_19_2_beta:
              ansible_host: 192.168.1.103
              ansible_port: 22
          vars:
            ansible_python_interpreter: /usr/bin/python3.8
      vars:
        ansible_ssh_private_key_file: /home/adminka/.ssh/asus_x751_ln