all:
  children:
    local:
      hosts:
        real_system:
          ansible_host: 127.0.0.1
          ansible_port: 40002

        control_node:
          ansible_host: 192.168.55.100

      children:
        virtual_box:
          hosts:
            linux_mint_19_2_beta:
              ansible_host: 192.168.56.100
