- name: Отправка ключей авторизации на virtual_box
  hosts: 'virtual_box'
  become: false

  vars:
    keys_from: "{{ ['real_system'] }}"  # впрочем :)

  tasks:
  - set_fact:
      ssh_ak: "{{ ssh_ak | default([]) + [lookup('file', key )] }}"
    vars: 
      key: "{{ hostvars[server]['orig_public_key'] }}"
    loop: "{{ keys_from }}"
    loop_control: { loop_var: server }
    delegate_to: "{{ server }}"

  - name: Отправка ключей
    vars:
      ssh_ak_string: "{{ ssh_ak | join('\n') }}"
    lineinfile:
      path: "~/.ssh/authorized_keys"
      line: "{{ ssh_ak_string }}"
      mode: 0644
      create: true


