---
# vars file

role_path: "{{ playbook_dir }}/roles/docker_control_node"
role_path_files: "{{ role_path }}/files"
role_path_templates: "{{ role_path }}/templates"

mode:
  start_node: "{{ start | default(false) | bool }}"
  stop_node: "{{ stop | default(false) | bool }}"
  restart_node: "{{ restart | default(false) | bool }}"
  rebuild_node: "{{ rebuild | default(false) | bool }}"
  drop_node: "{{ drop | default(false) | bool }}"
  start_stop_timeout_poll: [ 60, 1 ]
  rebuild_timeout_poll: [ 480, 5 ]
