---
# need installed rsync in ansible-machine
# - name: Fetch stuff from the remote and save to local
#   synchronize:  
#     src: "{{ }} "
#     dest: "{{ /logs-{{ inventory_hostname }}"
#     mode: pull

# alt way
- name: Получаем список файлов для копирования
  shell: (cd "{{ fetch_serv_src }}"; find . -maxdepth 1 -type f) | cut -d'/' -f2
  register: files_to_copy

- name: Скачиваем логи
  fetch: 
    src: "{{ fetch_serv_src }}/{{ item }}"
    dest: "{{ fetch_ansible_dest }}/{{ item }}"
    flat: yes
  with_items: "{{ files_to_copy.stdout_lines }}"