---
# --- Используется py скриптом ---

gsettings:
  org:
    # ------------------------------------------------------------------------------------------------------------------
    nemo:
      desktop:                                       # настройки отображения значков на раб. столе
        computer-icon-visible: "false"               # компьютер
        home-icon-visible: "false"                   # домашняя папка
        network-icon-visible: "false"                # сетевые подключения
        volumes-visible: "false"                     # примонтированные устройства
        desktop-layout: "true::true"                 # рабочего стола на остальных мониторах
        show-orphaned-desktop-icons: "true"          # значков с неактивных мониторов
      preferences:
        close-device-view-on-device-eject: "true"    # Закрывать вкладки, панели и окна носителя при отсоединении
        enable-mime-actions-make-executable: "true"  # Предлагать сделать файл исполняемым при попытке открытия неизвестного файла
        executable-text-activation: "display"        # Реакция на исполняемые текстовые файлы - Отобразить (открыть в текстовом редакторе)
        date-format: "iso"                           # Настройки управления файлами → Отображение → Дата (Формат → ISO)
        show-full-path-titles: "true"                # Показывать полный путь в заголовке окна
        show-hidden-files: "true"                    # Показывать скрытые файлы
        show-open-in-terminal-toolbar: "true"        # Отображать кнопку "Открыть в терминале" на панели инструментов
        show-reload-icon-toolbar: "true"             # Отображать кнопку "Обновить" на панели инструментов
        tooltips-in-icon-view: "true"                # Отображать подсказки в компактном режиме просмотра
        tooltips-show-mod-date: "true"               # Отображать дату изменения во всплывающих подсказках
        show-location-entry: "true"                  # Показывать адресную строку в формате ввода
        show-advanced-permissions: "true"            # Отображать дополнительные права в диалоге "Свойства файла"
        quick-renames-with-pause-in-between: "false" # Переименование файла при двойном нажатии по его имени
        tooltips-in-list-view: "false"               # Не отображать подсказки в режиме просмотра листом
        bulk-rename-tool: "b'gprename.sh'"           # Команда пакетного переименования  # 🎄
      list-view:
        default-visible-columns: "['name', 'date_modified', 'size', 'owner', 'permissions']"  # Отображение в виде "Список" столбцов
      window-state:
        sidebar-width: "206"                        # Ширина сайдбара
        network-expanded: "false"                   # Свернуть в боковой панели "сеть"
        start-with-menu-bar: "false"                # Скрыть меню бар
        start-with-status-bar: "false"              # Скрыть статус бар
      icon-view:
        captions: "['size', 'mime_type', 'owner']"  # Настройки управления файлами → Отображение → Подписи к значкам
                                                    # (Это приоритеты подписей при увеличении ZOOM в Nemo)
      plugins:
        disabled-actions: "['mint-sha256sum.nemo_action', 'clamav.nemo_action', 'media-info.nemo_action']"  # 🎄
    # ------------------------------------------------------------------------------------------------------------------
    cinnamon:
      alttab-switcher-style: "icons+thumbnails"     # Параметры системы → Окна → Alt+Tab → Тип переключения Alt-Tab →
                                                    # Значки и миниатюры
      # Горячие углы: активировать показ рабочего стола через 1 секунду (максимально допустимое значение)
      # при наведении в правый нижний угол; остальные углы — назначить по умолчанию и выключить
      hotcorner-layout: "['expo:false:0', 'scale:false:0', 'scale:false:0', 'desktop:true:1000']"
      workspace-osd-visible: 'false'                # OSD?
                                                    # Избранные приложения в меню Корицы  # 🎄
      favorite-apps: "['mintinstall.desktop', 'cinnamon-settings.desktop', 'org.gnome.Terminal.desktop', 'nemo.desktop']"

      desktop:
        media-handling:
          autorun-never: "true"                     # Выключить запуск программ при подключении носителей
        wm:
          preferences:
            action-scroll-titlebar: 'opacity'       # Параметры системы → Окна → Строка заголовка → Действие при
                                                    # прокрутке на заголовке колеса мыши → Настройка прозрачности
            button-layout: 'close,maximize,minimize,shade:menu'  # Параметры системы → Окна → Строка заголовка → Кнопки (по левой
                                                                 # стороне - закрыть, развернуть, свернуть, затенить; по правой - меню)
            min-window-opacity: '30'                # Параметры системы → Окна → Строка заголовка → Минимальная прозрачность 30% (по дефолту)
            theme: 'Mint-Y-Dark'                    # Рамки окон  # 🎄
            num-workspaces: '4'                     # Число рабочих мест (по дефолту - 4)
            workspace-names: "['Основная раб. область', 'Дополнительная раб. область', 'Развлечения', 'Прочее']"
        interface:
          icon-theme: 'Mint-Y-Aqua'                 # Тема значков  # 🎄
          cursor-theme: 'DMZ-Black'                 # Тема курсора (указатель мыши)  # 🎄
          gtk-theme: 'Mint-Y-Dark-Aqua'             # Тема gtk-theme (рабочий стол)  # 🎄
        notifications:
          bottom-notifications: 'true'              # Показывать уведомление в нижней части экрана
        sound:
          maximum-volume: "150"                     # Максимум звука
        privacy:
           remember-recent-files: "false"           # Не запоминать недавно открытые файлы
        a11y:
          keyboard:
            togglekeys-enable-beep: 'true'         # Включить звуковое оповещение при нажатии Caps и Num lock
            togglekeys-sound-on: '/usr/share/sounds/KDE-sounds/KDE-Sys-App-Positive.ogg'   # 🎄
            togglekeys-sound-off: '/usr/share/sounds/KDE-sounds/KDE-Sys-App-Negative.ogg'  # 🎄
                                               # <<< Управление мышь с помощью доп. цифр (отключено) >>>
            mousekeys-init-delay: '200'            # Первоначальные задержки
            mousekeys-accel-time: '2000'           # Время разгона
            mousekeys-max-speed: '500'             # Максимальная скорость
          mouse:
            secondary-click-enabled: 'true'        # Вкл. клик ПКМ
        screensaver:
          use-custom-format: "true"                # Включаем использование кастомного формата даты и времени
          time-format: '🎄❄️ Сегодня: 🎁🌟'          # Формат времени
          font-time: 'Ubuntu Medium 40'            # Шрифт времени
          date-format: '%d.%m.%y (%a), %H:%M '     # Формат даты
          font-date: 'Ubuntu 40'                   # Шрифт даты
          font-message: 'Ubuntu Light 18'          # Шрифт сообщения на экране блокировки
        background:
          picture-uri: 'file:///usr/share/backgrounds/Pack_image_v4/Asoka.png'  # обоина  # 🎄
      muffin:
        workspaces-only-on-primary: 'true'         # Использовать рабочие области только на основном мониторе
        workspace-cycle: 'true'                    # Пролистывание рабочих областей
      settings-daemon:
        plugins:
          power:
            button-suspend: 'nothing'              # Действие при нажатии кнопки сна
            button-hibernate: 'nothing'            # Действие при нажатии кнопки гибернации
            idle-dim-time: '660'                   # Затемнять экран при бездействии через 600 сек
                                                   # <<< Настройки для ноутбука >>>
            lid-close-ac-action: 'nothing'         # Действие при закрытии крышки → От сети → Бездействовать
            lid-close-battery-action: 'nothing'    # Действие при закрытии крышки → От батареи → Бездействовать
            critical-battery-action: 'nothing'     # Действие при критически низком заряде батареи → Бездействовать  # 🎄
            percentage-low: '20'                   # Уровень, который считается низким зарядом батареи (по умолчанию - 10)
            percentage-critical: '10'              # Уровень, который считается критическим зарядом батареи (по умолчанию — 3)
            percentage-action: '7'                 # При каком проценте выполнять действие при критическом разряде
        peripherals:
          keyboard:
            numlock-state: 'on'                    # Управление мышь с помощью доп. цифр???
    # ------------------------------------------------------------------------------------------------------------------
    x:
      editor:
        preferences:
          encodings:
                                                   # Совместимость кодировки с текстовыми файлами из Windows
            auto-detected: "['UTF-8', 'WINDOWS-1251', 'CURRENT', 'ISO-8859-15', 'UTF-16']"
          editor:                                  # <<< XED >>>
            highlight-current-line: "true"         # Подчеркивать текущую строку
            scheme: 'cobalt'                       # Стилевая схема — Cobalt
            display-line-numbers: "true"           # Показывать номера строк
        plugins:
                                                    # Набор включенных плагинов
          active-plugins: "['spell', 'time', 'sort', 'wordcompletion', 'filebrowser', 'textsize', 'modelines', 'docinfo', 'taglist']"
    # ------------------------------------------------------------------------------------------------------------------
    gnome:
      mousetweaks:
        click-type-window-geometry: ''             # Управление мышь с помощью доп. цифр???
        click-type-window-orientation: 'vertical'  # Управление мышь с помощью доп. цифр???
        click-type-window-style: 'both'            # Управление мышь с помощью доп. цифр???
      nm-applet:
        disable-connected-notifications: "true"    # Отключение уведомления о подключении к сети (Network Manager)
        disable-disconnected-notifications: "true" # Отключение уведомления об отключении от сети
      libgnomekbd:
        keyboard:
          layouts: "['us', 'ru']"                  # Настройки раскладки клавиатуры
          options: "['grp\tgrp:alt_shift_toggle', 'grp\tgrp:menu_switch']"  # Смена раскладки при Alt+Shift и Menu (пока зажата)
    # ------------------------------------------------------------------------------------------------------------------
    gtk:
      Settings:
        FileChooser:
          show-hidden: "true"                      # Показывать скрытые файлы (в немо)
    # blueberry:  # Выпилено в LM 21
      # obex-enabled: "false"                        # Не получать файлы от удаленных устройств bluetooth
  com:
    linuxmint:
      updates:
        show-size-column: 'true'                  # Отображать размер
        autorefresh-hours: '4'                    # apt update каждые 4 часа



