version: '3.8'

services:
    ansible_build:
      container_name: 'ansible_build'
      image: 'ansible:ssh'
      restart: 'no'
      ports:
        - 40003:22
      networks:
        net:
          ipv4_address: 192.168.55.100
      environment:
        - "SSH_HOST_RSA_KEY=${SSH_HOST_RSA_KEY}"
        - "SSH_HOST_RSA_PUBLIC_KEY=${SSH_HOST_RSA_PUBLIC_KEY}"
        - "SSH_AUTHORIZED_KEY=${SSH_AUTHORIZED_KEY}"
        - "USER_PASSWORD=${USER_PASSWORD}"
        - "SSH_HOST_RSA_KEY_NAME=${SSH_HOST_RSA_KEY_NAME}"
        - "SSH_HOST_RSA_PUBLIC_KEY_NAME=${SSH_HOST_RSA_PUBLIC_KEY_NAME}"
      volumes:
        - ~/General/Documents/Programming/Working_projects/ansible_build:/home/adminka/ansible_build:readonly
volumes:
  ansible_build:
    name: 'ansible_build'
networks:
    net:
      name: 'ansible_build_network'
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 192.168.55.0/24
