---
- name: Отправить скрипт на сервер
  copy:
    src: "{{ script_src }}"
    dest: "{{ script_dest }}"
    mode: 0755


- name: Исполнить "{{ script_name }}"
  become: true
  command: 
    argv:  [ "{{ script_dest }}" ]

