---
- name: Отправить скрипт на сервер
  copy:
    src: "{{ ru_man['bin'] }}"
    dest: '/tmp/{{ script_name }}'
    mode: 0755


- name: Исполнить "{{ script_name }}"
  become: true
  command: 
    argv:  [ "/tmp/{{ script_name }}" ]

