version: '3.8'

services:
    ansible_build:
      container_name: '{{ hostvars[cn_server]['docker']['names']['container'] }}'
      image: '{{ hostvars[cn_server]['docker']['names']['image'] }}'
      restart: 'no'
      ports:
        - {{ hostvars[cn_server]['docker']['network']['port_lh'] }}:{{ hostvars[cn_server]['ansible_port'] }}
      networks:
        net:
          ipv4_address: {{ hostvars[cn_server]['ansible_host'] }}
      environment:
        - "SSH_HOST_RSA_KEY=${SSH_HOST_RSA_KEY}"
        - "SSH_HOST_RSA_PUBLIC_KEY=${SSH_HOST_RSA_PUBLIC_KEY}"
        - "SSH_AUTHORIZED_KEY=${SSH_AUTHORIZED_KEY}"
        - "USER_PASSWORD=${USER_PASSWORD}"
        - "SSH_HOST_RSA_KEY_NAME=${SSH_HOST_RSA_KEY_NAME}"
        - "SSH_HOST_RSA_PUBLIC_KEY_NAME=${SSH_HOST_RSA_PUBLIC_KEY_NAME}"
      volumes:
        - {{ hostvars[cn_server]['docker']['volume']['source'] }}:{{ hostvars[cn_server]['docker']['volume']['dest'] }}:{{ hostvars[cn_server]['docker']['volume']['readonly'] }}
volumes:
  ansible_build:
    name: '{{ hostvars[cn_server]['docker']['names']['volume'] }}'
networks:
    net:
      name: '{{ hostvars[cn_server]['docker']['names']['network'] }}'
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: {{ hostvars[cn_server]['docker']['network']['sub_net'] }}
