---
user:
  uid: '1000'
  gid: '1001'
  ssh_rsa: "{{ lookup('file', orig_private_key ) }}"
  ssh_rsa_p: "{{ lookup('file', orig_public_key ) }}"
  ssh_ak: "{{ lookup('file', orig_public_key ) }}"
  ssh_rsa_name: "{{ orig_private_key | basename }}"
  ssh_rsa_p_name: "{{ orig_public_key | basename }}"


docker:
  names:
    container: 'ansible_build'
    image: 'ansible:ssh'
    volume: 'ansible_build'
    network: 'ansible_build_network'
  volume:
    source: "~/General/Documents/Programming/Working_projects/ansible_build"
    dest: "{{ lookup('env','HOME') + '/ansible_build' }}"
    readonly: 'readonly'
  network:
    sub_net: '192.168.55.0/24'
    port_lh: '40003'