---
- name: Обновление apt кэша
  apt:
    update_cache: yes
    cache_valid_time: 1800  # 30 min

- name: Получение очередной категории программ
  include_tasks: apt_install/package_from_category_[1].yml
  with_items: "{{ apt_install }}"
  loop_control:
    loop_var: category
  when: apt_install_settings['category_enabled'][category] | bool

