---
# tasks file for install_from_repo

- name: Импорт инструкций удаления
  include_tasks: apt_uninstall.main.yml
  when: apt_uninstall_settings['need_uninstall'] | bool

- name: Импорт инструкций установки
  include_tasks: apt_install.main.yml
  when: apt_install_settings['need_install'] | bool
