---
# install recommended_dependencies
- name: Обновление apt кэша
  apt:
    update_cache: yes
    cache_valid_time: 1800  # 30 min
  become: true

- name: "sudo apt install {{ apt_packages }}"
  apt:
    name: "{{ apt_packages.split() }}"
    state: latest
  become: true
  ignore_errors: yes

- name: "sudo pip install {{ pip_packages }}"
  pip:
    name: "{{ pip_packages.split() }}"
    state: latest
  become: true
  ignore_errors: yes