---
# 1. Копируем ссылки на интересующие нас апплеты
#    отсюда https://cinnamon-spices.linuxmint.com/applets

- name: Создание технических директорий
  file:
    path: "{{ item[1] }}" 
    state: "{{ item[0] }}" 
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  loop:
    - ['directory', "{{ cinnamon_panel.new_applets.dir_to_download }}"]
    - ['directory', "{{ cinnamon_panel.sys_local }}"]
    - ['directory', "{{ cinnamon_panel.sys_locale }}"]
    - ['directory', "{{ cinnamon_panel.sys_configs }}"]


- name: Загрузка, распаковка
  vars:
    dir_to_download: "{{ cinnamon_panel.new_applets.dir_to_download }}"
  include_tasks: applets/wget_[1].yml
  with_items: "{{ cinnamon_panel.new_applets.applets }}"
  loop_control:
    loop_var: applet
  when: cinnamon_panel['new_applets']['need_download'] | bool
