---
# tasks file

- block:

    # что можно улучшить:
    # проблему с путями: ~/.config/cinnamon/spices/  (in 19.3 = ~/.cinnamon/configs/ )
    # нумлок апплет

  - name: Получение новых апплетов из сети и распаковка в юзер зону
    include_tasks: applets/wget_loop.yml

  - name: Установка рекомендуемых зависимостей
    vars:
      apt_packages: "{{ cinnamon_panel['new_applets']['recommended_dependencies']['apt'] | join(' ') }}"
      pip_packages: "{{ cinnamon_panel['new_applets']['recommended_dependencies']['pip'] | join(' ') }}"
    include_tasks: applets/dependencies.yml
    when: cinnamon_panel['new_applets']['recommended_dependencies']['need_install'] | bool

  - name: Применение скрипта для настройки панелей, используя gsettings
    vars:
      filedir_to_copy_serv_src: "{{ cinnamon_panel['need_send_to_remote_src'] }}"
      filedir_to_copy_serv_dest: "{{ cinnamon_panel['need_send_to_remote_dest'] }}"
      script_name: "{{ cinnamon_panel['integration_of_applets_configuration'] }}"
    include_tasks: features/send_dir_and_exec_script.yml

  - name: Установка KDE звуковой схемы (для pomodoro@gregfreeman.org)
    vars:
      filename: "{{ cinnamon_panel['new_applets']['sounds_for_pomodoro']['file'] }}"
      file_path: "{{ cinnamon_panel['new_applets']['dir_to_download'] }}/{{ filename }}"
      dest: "{{ cinnamon_panel['new_applets']['sounds_for_pomodoro']['dest'] }}"
    include_tasks: applets/sounds_for_pomodoro.yml


  when: cinnamon_panel['need_settings'] | bool

- block:

  - name: Установка gsettings схем
    vars:
      filedir_to_copy_serv_src: "{{ cinnamon_gsettings['need_send_to_remote_src'] }}"
      filedir_to_copy_serv_dest: "{{ cinnamon_gsettings['need_send_to_remote_dest'] }}"
      script_name: "{{ cinnamon_gsettings['script_name'] }}"
    include_tasks: features/send_dir_and_exec_script.yml

  - name: Получение папки логов
    vars:
      fetch_serv_src: "{{ cinnamon_gsettings['need_send_to_remote_dest'] }}/logs/"
      fetch_ansible_dest: "{{ cinnamon_gsettings['need_send_to_remote_src'] }}/logs/{{ inventory_hostname }}"
    include_tasks: features/fetch_dir.yml
    when: true

  when: cinnamon_gsettings['apply'] | bool