---
# vars file for install_from_repo


apt_install_settings:
  max_priority_for_install: 5
  force_install: true  # ingore need_install (for debug)
  category_enabled:
    system_utils: true

# \n
# \n    - package:
# \n      description: ''\n      need_install: true\n      priority: 5\n\n

apt_install:
  system_utils:
    - package: advancecomp
      description: 'оптимизация png'
      need_install: true
      priority: 2

    - package: alien
      description: 'rmp в deb'
      need_install: false
      priority: 4

    - package: d-feet
      description: 'd-bus просмотрщик'
      need_install: true
      priority: 3

    - package: dconf-editor
      description: 'редактор настроек среды'
      need_install: true
      priority: 3

    - package: elinks
      description: 'консольный браузер'
      need_install: true
      priority: 4

    - package: firefox-locale-ru
      description: 'перевод FF на русский'
      need_install: true
      priority: 1

    - package: fortunes fortunes-ru
      description: 'анекдоты'
      need_install: true
      priority: 5

    - package: gimp-help-ru
      description: ''
      need_install: true
      priority: 5

    - package: git,
      description: ''
      need_install: true
      priority: 1

    - package: gnome-commander
      description: 'милый и быстрый файловый менеджер'
      need_install: true
      priority: 5

    - package: gpm
      description: 'поддержка мыши в tty'
      need_install: true
      priority: 5

    - package: gprename
      description: 'пакетное переименование файлов'
      need_install: true
      priority: 2

    - package: grml-rescueboot
      description: 'загрузка с iso в grub'
      need_install: true
      priority: 3

    - package: hardinfo
      description: 'информация о компе и системе'
      need_install: true
      priority: 5

    - package: htop
      description: 'консольный вывод процессов'
      need_install: true
      priority: 3

    - package: jarwrapper
      description: 'запуск исполняемых файлов jar'
      need_install: true
      priority: 5

    - package: jpegoptim
      description: 'оптимизация jpg'
      need_install: true
      priority: 2

    - package: k3b k3b-extrathemes k3b-i18n
      description: 'программа для прожига дисков'
      need_install: false
      priority: 4

    - package: language-pack-gnome-ru
      description: 'руссификация'
      need_install: true
      priority: 1

    - package: mat
      description: 'очистка метаданных'
      need_install: true
      priority: 2

    - package: meld
      description: 'сравнение файлов и каталогов'
      need_install: true
      priority: 1

    - package: mintnanny
      description: 'блокировщик доменов'
      need_install: true
      priority: 5

    - package: ncdu
      description: 'консольный вывод размера файлов/папок'
      need_install: true
      priority: 2

    - package: nemo-audio-tab
      description: 'вкладка Звук (ПКМ по файлу --> Свойства); позволяет посмотреть метаданные аудиофайла'
      need_install: true
      priority: 4

    - package: nemo-compare
      description: 'км Сравнить; использует meld для сравнения файлов и папок'
      need_install: true
      priority: 1

    - package: nemo-filename-repairer
      description: 'км для восстановления кодировки в названии каталогов'
      need_install: true
      priority: 5

    - package: nemo-gtkhash
      description: 'вкладка Хэши (ПКМ по файлу --> Свойства)'
      need_install: true
      priority: 5

    - package: nemo-image-converter
      description: 'два КМ: Масштабировать изображения и Вращать изображения'
      need_install: true
      priority: 4

    - package: nemo-media-columns
      description: 'метаданные музыки/EXIF и PDF при отображении файлов списком (Ctrl+2)'
      need_install: true
      priority: 5

    - package: nemo-pastebin
      description: 'км для отправки текста на pastebin'
      need_install: true
      priority: 5

    - package: network-manager-l2tp-gnome
      description: 'поддержка l2tp'
      need_install: false
      priority: 5

    - package: openjdk-8-jre
      description: 'среда запуска java приложений'
      need_install: true
      priority: 5

    - package: optipng
      description: 'оптимизация png'
      need_install: true
      priority: 2

    - package: papirus-icon-theme
      description: 'темы иконок'
      need_install: false
      priority: 5

    - package: qpxtool
      description: 'тест качества cd/dvd дисков'
      need_install: true
      priority: 4

    - package: rar
      description: 'архиватор'
      need_install: true
      priority: 2

    - package: scons
      description: 'усовершенствованный make'
      need_install: true
      priority: 5

    - package: screenfetch
      description: 'вывод информации о системе'
      need_install: true
      priority: 4

    - package: thunderbird-locale-ru
      description: 'русский язык для thunderbird'
      need_install: true
      priority: 4

    - package: tree
      description: 'выводит каталоги в форме дерева'
      need_install: true
      priority: 4

    - package: ttf-mscorefonts-installer
      description: 'шрифты молокософта'
      need_install: true
      priority: 1

    - package: virtualbox-ext-pack virtualbox-qt
      description: 'визуализация ос-м'
      need_install: true
      priority: 3

    - package: xclip
      description: 'для копирования информации из терминала в буфер '
      need_install: true
      priority: 5

    - package: yad
      description: 'аналог zenity, только круче'
      need_install: true
      priority: 3
