---
# vars file for install_from_repo


apt_install_settings:
  max_priority_for_install: 5
  category_enabled:
    system_utils: true


apt_install:
  system_utils:
    - package: advancecomp,
      description: 'Оптимизация png'
      need_install: true
      priority: 5

    - package: alien,
      description: ''
      need_install: false
      priority: 5

